version: '3'
services:
  yii2-php:
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ./.composer-cache:/root/.composer/cache
      - ./:/app
    ports:
      - '8000:80'
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=basic
      - POSTGRES_USER=basic
      - POSTGRES_PASSWORD=123
